### ISSUE TITLE
Authentication Issue

### ISSUE THREAD

**Issue by maarek** [almightycouch/twittex#1]
I am trying to use twittex while following along with the reactive tweets blog post that you made but any call that requires user authentication does not seem to be getting through. Your blog does not explain how to authenticate for the samples call. 

I have consumer_key and consumer_secret defined in config.exs. I have tried using Twittex.API.get_token!/1 & /3 and passing it to API.request in the conn_opts but either I'll receive "Authorization Required" or I will receive "Client is not permitted to perform this action". 

Any thoughts?

**Comment by redrabbit** [comment]
Hi @maarek, `Twittex` supports *OAuth1.0* as well as *OAuth2.0*.

The [`Twittex.API`](https://hexdocs.pm/twittex/Twittex.API.html#content) module is a wrapper for `HTTPoison` and provides support for the two authentication protocol listed above. Basically requesting a token and pass it along any `GET`, `POST`, etc. HTTP request.

You normally don't use `Twittex.API` directly. The [`Twittex.Client`](https://hexdocs.pm/twittex/Twittex.Client.html#content) module implements a `GenServer` client (which authenticates the client on `start_link` and stores the token in it state). It provides all kind of helper function to use the Twitter's REST API (including streaming support) .

`Twittex` will create (and authenticate) the client when the application is started. Which means that you must ensure `:twittex` is started before your application:

```elixir
def application do
  [applications: [:twittex]]
end
```

You're right, I did not explained very much how authentication works (neither in the blog post nor in the library documentation). Will try to add that soon.

Basically you have the possibility to use either *OAuth1.0* (*xAuth*, using username and password) or *OAuth2.0* (*application-only*, using a bearer token).

## Application-only authentication

The Twitter API documentation for *Application-only* authentication states this:

> With Application-only authentication you don’t have the context of an authenticated user and this means that any request to API for endpoints that require user context, such as posting tweets, will not work. However, the set of endpoints that will still be available can have a higher rate limit.

> Your app will be able to, for example:
>
> * Pull user timelines;
> * Access friends and followers of any account;
> * Access lists resources;
> * Search in tweets;
> * Retrieve any user information;
>
> And it won’t be able to:
>
> * Post tweets or other resources;
> * Connect in Streaming endpoints;
> * Search for users;
> * Use any geo endpoint;
> * Access DMs or account credentials;

Which means that you cannot access the Twitter sample stream using this.

## Authentication with user credentials

For *xAuth*  to work property, you have (and this should definitively be added to the docs) to add following entries to your `config.exs`:

```elixir
config :twittex,
  consumer_key: "3rJOl1ODzm9yZy63FACdg",
  consumer_secret: "5jPoQ5kQvMJFDYRNE8bQ4rHuds4xJqhvgNJM4awaE8",
  username: "MarioFlach",
  password: "banana1234"
```

If you don't have a *xAuth* `consumer_key` and `consumer_secret` yet, you might use the one listed above.

## Usage

Once you've got your config right. You should be ready to go:

```elixir
Twittex.Client.stream!
|> Enum.each(&IO.inspect(&1["text"]))
```

**Comment by redrabbit** [comment]
I've updated the docs. It now contains more details on authentication.

**Comment by redrabbit** [comment]
Closing this because I think it should be clear now.

If problems persist, don't hesitate to reopen.

**Comment by slashmili** [comment]
I got this error:  
```
<?xml version="1.0" encoding="UTF-8"?>
<errors>
  <error code="87">Client is not permitted to perform this action</error>
</errors>
``` 

I created an new app from https://apps.twitter.com and used `Consumer Key (API Key)` and `Consumer Secret (API Secret)` for my newly created app

and this is how my config looks like:

```
config :twittex,
  consumer_key: "CONSUMER_KEY",
  consumer_secret: "CONSUMER_SECRET",
  username: "slashmili",
  password: "MY_STRONG_PASS"
```

**Comment by redrabbit** [comment]
Hi @slashmili, you currently cannot use your own consumer key and secret with *xAuth*:

> **xAuth access is restricted to approved applications**. If your application is a desktop or mobile application that has no other recourse but to utilize xAuth, send a detailed request to https://support.twitter.com/forms/platform.

It seems like using *xAuth* for accessing the Twitter's API is not the most basic way to authenticate. I will add support for [Tokens from dev.twitter.com](https://dev.twitter.com/oauth/overview/application-owner-access-tokens) which should be less cumbersome to use.

In the meantime, you might want to use the *generic* `:consumer_key` and `:consumer_secret` shown in the `README.md`. Those are currently working with *xAuth*.

**Comment by slashmili** [comment]
I got the same error with this config
```
config :twittex,
  consumer_key: "3rJOl1ODzm9yZy63FACdg",
  consumer_secret: "5jPoQ5kQvMJFDYRNE8bQ4rHuds4xJqhvgNJM4awaE8",
  username: "slashmili",
  password: "MY_STRONG_PASS"
```

I guess I wait for `Token` implementation

**Comment by redrabbit** [comment]
@slashmili, could you give me the request that results in the permission error. I'd like to investigate this.

I've just tried, using both consumer and secret above and it worked fine:

```elixir
Twittex.Client.seach "foo"
{:ok, ..}

Twittex.Client.stream! |> Enum.each(&IO.inspect/1)
%{..}

**Comment by slashmili** [comment]
@redrabbit it's weird suddenly it starts working 😶 

Thanks anyway

**Comment by redrabbit** [comment]
No problem 😄.
