### ISSUE TITLE
Add support for authentication with token from dev.twitter.com

### ISSUE THREAD

**Issue by redrabbit** [almightycouch/twittex#2]
As *xAuth* is not the most trivial way to access the API (access is restricted to approved applications), this will provide a third way (see #1) to authenticate:

* Application-only
* User-credentials using *xAuth*
* Access tokens from http://dev.twitter.com

**Comment by faebser** [comment]
I'm currently working on a project where I need to access to a twitter feed as stream. I opened a pull request over here: https://github.com/almightycouch/twittex/pull/5
